[scrolling]
history = 100_000

[font]
size = 12.0
normal = {family = "JetBrains Mono", style = "Regular"}

[cursor]
vi_mode_style = "Block"
style = {blinking = "Off", shape = "Beam"}
unfocused_hollow = true

[keyboard]
bindings = [
  {action = "SpawnNewInstance", key = "Return", mods = "Control|Shift"} ,
]

[general]

live_config_reload = true
import = [
  "~/.config/alacritty/colors.toml",
]

