[colors.primary]
background = '0x11111B'
foreground = '0xCDD6F4'

[colors.normal]
black   = '0x45475A'
red     = '0xF38BA8'
green   = '0xA6E3A1'
yellow  = '0xF9E2AF'
blue    = '0x89B4FA'
magenta = '0xF5C2E7'
cyan    = '0x94E2D5'
white   = '0xBAC2DE'

[colors.bright]
black   = '0x585B70'
red     = '0xF38BA8'
green   = '0xA6E3A1'
yellow  = '0xF9E2AF'
blue    = '0x89B4FA'
magenta = '0xF5C2E7'
cyan    = '0x94E2D5'
white   = '0xA6ADC8'
