theme = "dracula"

[editor]
true-color = true
middle-click-paste = true
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true
auto-pairs = true
auto-format = false
insert-final-newline = false
popup-border = "all"
jump-label-alphabet = "hjklabcdefgimnopqrstuvwxyz"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "n"
mode.insert = "i"
mode.select = "v"
separator = " "
left = ["mode", "separator", "register", "version-control", "separator", "spinner"]
center = ["read-only-indicator", "file-name", "file-modification-indicator", "read-only-indicator"]
right = ["diagnostics", "selections", "primary-selection-length", "position", "file-encoding", "file-type"]

[editor.lsp]
display-messages = true
goto-reference-include-declaration = false

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[keys.normal]
# Do not append '\b' to '*' register value
"*" = "search_selection"
"A-*" = ":noop"

# Global search word under current cursor
"tab" = '@miw*<space>/<ret>'

# Next/Previous items from the last picker
"]"."'" = "@<space>'<C-n><ret>"
"["."'" = "@<space>'<C-p><ret>"

# Buffer management
C-n = [':new']
C-del = [":buffer-close"]
C-j= "goto_previous_buffer"
C-k= "goto_next_buffer"

ret = "goto_word"
Y = [":yank-join"]

C-g = [":sh fish ~/.config/helix/helix.fish blame %{buffer_name} %{cursor_line}"]

[keys.normal."C-r"]
C-r = [":reload"]
C-R = [":reload-all"]

[keys.normal.space.c]
l = ":o ~/.config/helix/languages.toml"
o = ":config-open"
r = ":config-reload"

[keys.select]
"*" = "search_selection"
"A-*" = ":noop"
"tab" = '@miw*<space>/<ret>'
C-del = [":buffer-close"]
C-n = [':new']
ret = "goto_word"
Y = [":yank-join"]
