theme = "dracula"

[editor]
true-color = true
middle-click-paste = true
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true
auto-pairs = true
auto-format = false
jump-label-alphabet = "hjklabcdefgimnopqrstuvwxyz"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "n"
mode.insert = "i"
mode.select = "v"
separator = " "
left = ["mode", "separator", "register", "version-control", "separator", "spinner"]
center = ["read-only-indicator", "file-name", "file-modification-indicator", "read-only-indicator"]
right = ["diagnostics", "selections", "primary-selection-length", "position", "file-encoding", "file-type"]


[editor.lsp]
display-messages = true
goto-reference-include-declaration = false

[editor.file-picker]
hidden = false

[keys.normal."C-r"]
C-r = [":reload"]
C-R = [":reload-all"]

[keys.normal.space.c]
l = ":o ~/.config/helix/languages.toml"
o = ":config-open"
r = ":config-reload"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[keys.normal]
C-j= "goto_previous_buffer"
C-k= "goto_next_buffer"
ret = "goto_word"
C-del = [":buffer-close"]
C-n = [':new']
Y = [":yank-join"]

"]"."'" = "@<space>'<C-n><ret>" # Next item from last picker
"["."'" = "@<space>'<C-p><ret>" # Prev item from last picker

# This is kinda broken, but screw it
C-g = [":sh cd $(dirname %{buffer_name}) && git blame --line-porcelain $(basename %{buffer_name}) -L %{cursor_line},%{cursor_line}"]


[keys.select]
ret = "goto_word"
C-del = [":buffer-close"]
Y = [":yank-join"]
C-n = [':new']
