theme = "dracula"

[editor]
true-color = true
middle-click-paste = true
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true
auto-pairs = true
auto-format = false
jump-label-alphabet = "hjklabcdefgimnopqrstuvwxyz"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "n"
mode.insert = "i"
mode.select = "v"
separator = " "
left = ["mode", "separator", "register", "version-control", "separator", "spinner"]
center = ["read-only-indicator", "file-name", "file-modification-indicator", "read-only-indicator"]
right = ["diagnostics", "selections", "primary-selection-length", "position", "file-encoding", "file-type"]


[editor.lsp]
display-messages = true
goto-reference-include-declaration = false

[editor.file-picker]
hidden = false

[keys.normal.space.c]
l = ":o ~/.config/helix/languages.toml"
o = ":config-open"
r = ":config-reload"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[keys.normal]
C-j= "goto_previous_buffer"
C-k= "goto_next_buffer"
ret = "goto_word"

# This is kinda broken, but screw it
C-g = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output lazygit',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':set mouse false',
  ':set mouse true',
  ':redraw',
]

[keys.select]
ret = "goto_word"
