[language-server.csharp]
# cargo install --git https://github.com/SofusA/csharp-language-server
command = "csharp-language-server"

[[language]]
name = "c-sharp"
language-servers = ["csharp"]
file-types = ["cs", "csproj", "sln"]
auto-format = false

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
language-servers = [ "ty", "ruff", "pylsp" ]

[[language]]
name = "renode-repl"
scope = "source.repl"
comment-tokens = ['//']
file-types = ["repl"]

