#!/usr/bin/env bash

SCRIPT_PATH=$(dirname "$(realpath -s "$BASH_SOURCE")")
CONFIG_FILE="$SCRIPT_PATH/config"
MODULES_DIR="$SCRIPT_PATH/config.d"

# List configuration modules
echo "The following modules will be merged:"
ls -1 $MODULES_DIR

# Merge all configuration modules
echo "# !!! AUTOGENERATED FILE !!! DO NOT EDIT #" > $CONFIG_FILE
cat $MODULES_DIR/* >> $CONFIG_FILE

# Reload i3
i3-msg reload 1>/dev/null
